name: Build and Deploy PDFs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live and latexmk
        run: |
          sudo apt-get update
          # You may not need the full texlive-full if your documents are modest.
          sudo apt-get install -y texlive-full latexmk

      - name: Compile all LaTeX documents
        run: |
          find . -type f -name "*.tex" -not -path "./public/*" -print0 | while IFS= read -r -d '' texfile; do
            echo "Compiling ${texfile}..."
            latexmk -pdf -silent "${texfile}"
          done

      - name: Prepare deployment directory
        run: |
          mkdir -p public
          rm -f public/*.pdf
          find . -type f -name "*.pdf" -not -path "./public/*" -exec cp {} public/ \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
